### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [CastilloDelgado/neubox_challenge_js#2]
Te comparto la ejecución de los casos de prueba.

Resultados: Marco Castillo
Ciclo: 2

Problema 1: Js
P1-CP1-EntradaEjemplo: Fail
P1-CP1-EntradaCorrecta: Pass
P1-CP2-LongitudLinea1Invalida: Pass
P1-CP3-LongitudLinea2Invalida: Pass
P1-CP4-LongitudMensajeInvalido: Pass
P1-CP5-LongitudMensajeMenor3: Pass
P1-CP6-LongitudMensajeMayor5000: Pass
P1-CP7-LongitudInstruccion1Menor2: Pass
P1-CP8-LongitudInstruccion2Menor2: Pass
P1-CP9-CaracteresInvalidosMensaje: Pass
P1-CP10-LongitudInstruccion1Mayor50: Pass
P1-CP11-LongitudInstruccion2Mayor50: Pass
P1-CP12-DosInstruccionesEnMensaje: Fail
P1-CP13-InstruccionCaracterRepetido: Fail

Problema 2: Js
- La lógica de la solución no es correcta, volver a revisar el problema
P2-CP01-Ejemplo: Pass
P2-CP02-G27282: Fail
P2-CP03_G16102: Fail
P2-CP04-RondasMayoresAEntrada: Pass
P2-CP05-RondasMenoresAEntrada: Pass
P2-CP06-CaracteresEnNumeroRondas: Pass
P2-CP07-CaracteresEnValorRonda: Pass
P2-CP08-OK-Limite-10000: Pass
P2-CP09-DesbordeDeValoresRonda: Pass

**Comment by CastilloDelgado** [comment]
Buen día, una disculpa por la tardanza, no había podido revisar la actualización.

**Problema 1:**
- Se agrega validación de caracteres duplicados en cada mensaje
- Se agrega validación para máximo 1 mensaje por cadena

**Problema 2:**
- Encontre el problema con la lógica, no estaba haciendo el acumulado de los puntajes.
- Se agrega el acumulado de los puntajes.
